name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Create Deployment Zip
        run: |
          zip -r deployment.zip . -x '*.git*'

      - name: Upload Zip to S3
        run: |
          aws s3 cp deployment.zip s3://cmtr-l3nbneha-deployments-842675975772/deployment-${{ github.sha }}.zip

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name cmtr-l3nbneha-app \
            --deployment-group-name cmtr-l3nbneha-dg \
            --s3-location bucket=cmtr-l3nbneha-deployments-842675975772,key=deployment-${{ github.sha }}.zip,bundleType=zip \
            --region eu-west-1